- hdf5-rs/src/hl/container.rs
- hdf5-rs/src/hl/dataset.rs
- hdf5-rs/src/hl/space.rs
- hdf5-rs/tests/common/gen.rs
- hdf5-rs/tests/test_dataset.rs
Add a reader method that supports fetching ndarray slices out of a dataset, letting the user avoid reading the entire dataset. Any feedback on the general approach?  If it seems like we're on the right track here I'll 1-d and 2-d special cases and writer support.
TODOs:
> read_slice() / write_slice() methods to permit dataset slice IO

- hdf5-rs/src/hl/container.rs
- hdf5-rs/src/hl/space.rs
- hdf5-rs/tests/test_dataset.rs
@aldanor  Thanks for reviewing this. I think I've fixed all the issues raised in #26 :
> 1. First I've tried `pixels.read_slice_1d::<Pixel>(s![.., 1])`, which failed to compile:
>    ```
>    no method named `read_slice_1d` found for type `h5::hl::dataset::Dataset`
>    ```
Added these methods to Dataset.
>    Slicing API should really be accessible directly from datasets; but that we can fix pretty easily.
> 2. Ok, next try: `pixels.as_reader().read_slice_1d::<Pixel>(s![.., 1])`, also fails to compile:
>    ```
>    wrong number of type arguments: expected 2, found 1
>    ```
>    Now this one's not very nice, having to provide a `_` placeholder for a second type is counter-intuitive and may lead to problems with type inference.
Here's the `ndarray` slice method: …
> Some fixes for slice API

- CHANGELOG.md
- hdf5-rs/src/dim.rs
- hdf5-rs/src/hl/container.rs
- hdf5-rs/src/hl/dataset.rs
- hdf5-rs/src/hl/datatype.rs
- hdf5-rs/src/hl/file.rs
- hdf5-rs/src/hl/group.rs
- hdf5-rs/src/hl/location.rs
- hdf5-rs/src/hl/object.rs
- hdf5-rs/src/hl/plist.rs
- hdf5-rs/src/hl/plist/file_create.rs
- hdf5-rs/src/hl/space.rs
Closes #23.
`Clone` now acts as a shallow ref copy (same way as it works with Rc/Arc/etc).
Property lists and dataspaces now have a separate `.copy()` method which performs a deep copy.
Open question: should `.copy()` return a `Result<Self>`, or should it return `Self` (like it was previously with `Clone`), where the object may contain an invalid handle?
> Make all high-level objects cloneable

- CHANGELOG.md
- README.md
- hdf5-derive/src/lib.rs
- hdf5-sys/build.rs
- rustfmt.toml
- src/handle.rs
- src/hl/dataset.rs
- src/hl/file.rs
- src/hl/location.rs
- src/test.rs
- tests/common/util.rs
This is certainly a breaking change, but better sooner than later (initial discussion with @Enet4 a while ago in #14).
Main points:
- FAPL and FCPL bindings are pretty much 100% complete, it's a shame they couldn't have been used until now; this is now fixed, the new FileBuilder has full access to those (!).
- String-based modes like "r" and "w" are gone. Instead, you can just use `File::open()`, `File::open_rw()`, `File::create()`, `File::create_excl()` and `File::append()` (FileBuilder has those methods two as finishers).
- In case of need, there's also `File::open_as()` which mimics previous behaviour, but is strongly typed and doesn't use string-based modes either (FileBuilder has it too).
- Special cases like driver strings etc are gone from the new FileBuilder, instead you can …
> File constructor / FileBuilder API rework

- hdf5-sys/src/h5d.rs
These "optimized functions" are missing from the documentation but have been part of the public API since 1.10.3.
https://www.hdfgroup.org/2018/08/hdf5-1-10-3-release-newsletter-164/
> hdf5-sys: Add missing H5Dread_chunk and H5Dwrite_chunk functions

- Cargo.toml
- hdf5-sys/Cargo.toml
By setting metadata in `Cargo.toml` (https://docs.rs/about#metadata), where we build hdf5 statically, we get documentation for "free" on `docs.rs`. We no longer have to build and deploy the documentation ourselfs.
@aldanor This would be a great PR to merge before the next release!
> Configure the docs.rs build

- hdf5-types/src/lib.rs
- hdf5-types/src/string.rs
- src/hl/container.rs
- src/hl/plist.rs
The allocator functions are not protected by a mutex, as the reentrant mutex is defined in `hdf5` which we can't depend on. Is there a way of moving this mutex to `hdf5-sys`? Should we instead move `hdf5-types` to a module within `hdf5`'?
CI results are available at https://github.com/magnusuMET/hdf5-rust/runs/945773746?check_suite_focus=true
Fixes #104
> Use hdf5 allocator

- .github/workflows/ci.yml
- hdf5-sys/build.rs
- hdf5-sys/src/h5f.rs
- hdf5-sys/src/h5i.rs
- hdf5-sys/src/h5l.rs
- hdf5-sys/src/h5o.rs
- hdf5-sys/src/h5p.rs
- hdf5-sys/src/h5pl.rs
- hdf5-sys/src/h5r.rs
- hdf5-sys/src/h5s.rs
- hdf5-sys/src/h5t.rs
- hdf5-sys/src/h5vl.rs
- hdf5-sys/src/lib.rs
- src/hl/group.rs
Add the newest changes according to https://portal.hdfgroup.org/display/HDF5/Software+Changes+from+Release+to+Release+for+HDF5-1.12. Currently compiles and tests complete sucessfully on all platforms but new functions are not tested nor used anywhere.
Fixes #94
> Add 1.12.0 support

- .github/workflows/ci.yml
- hdf5-src/build.rs
Use wine to run HDF5 configuration programs.
To run Windows unit tests on Linux, use wine as the runner. For example:
```
CARGO_TARGET_X86_64_PC_WINDOWS_GNU_RUNNER=wine64 cargo test --features hdf5-sys/static --target x86_64-pc-windows-gnu
```
If your main wine configuration is 32-bit but you're cross-compiling for 64-bit windows, you will need to specify a different wine environment using the `WINEPREFIX` environment variable, eg. `WINEPREFIX=~/wine_win64`.
> Support static cross-compilation from Unix to Windows.

- .github/workflows/ci.yml
- hdf5-types/Cargo.toml
- hdf5-types/src/array.rs
- hdf5-types/src/lib.rs
Const generics are rapidly approaching which means `impl_array` can be replaced with a generic size, supporting more array cases than one can manually specify. This is feature gated on `const_generics` on `hdf5-types` and should only be a minor bump.
Ref #122
> use const generics in hdf5-types for array impl

- CHANGELOG.md
- Cargo.toml
- hdf5-sys/Cargo.toml
- hdf5-types/Cargo.toml
- hdf5-types/src/string.rs
- src/test.rs
- tests/common/gen.rs
- tests/test_datatypes.rs
- tests/test_plist.rs
This updates `parking_lot` to the newest version, and `ndarray` can now be both `0.13` and `0.14` as we expose this publicly.
Other internal dependencies are updated to deduplicate the dependency graph:
* `tempdir` is replaced with the more up to date `tempfile` to pull in the newest version of `rand`.
* `mashup` is replaced with `paste` to pull `proc-macro2`
This result in `cargo tree -d` returning empty
Closes #125
Closes #123
> Bump dependencies

- CHANGELOG.md
- src/dim.rs
Add a `?Sized` bound to the `Dimension` implementation for `&T` to ensure that unsized slices can be used as shape.
I also added a small `slice_as_shape` test function that only compiles with the `?Sized` bound.
> Implement Dimension for slices

- CHANGELOG.md
- README.md
- hdf5-derive/tests/test.rs
- hdf5-types/src/array.rs
- hdf5-types/src/dyn_value.rs
- hdf5-types/src/h5type.rs
- hdf5-types/src/lib.rs
- hdf5-types/src/string.rs
- tests/common/gen.rs
- tests/test_datatypes.rs
- tests/test_plist.rs
This removes a layer of indirection and drops the `u8` type from the string types. Introduces breaking changes, and would be nice to include in the next version.
Fixes #143
> Replace Array trait with const generics

- .github/workflows/ci.yml
- CHANGELOG.md
- hdf5-src/Cargo.toml
- hdf5-src/build.rs
- hdf5-sys/Cargo.toml
- hdf5-sys/build.rs
- hdf5-sys/src/h5.rs
- hdf5-sys/src/h5fd.rs
- hdf5-sys/src/h5p.rs
- hdf5-sys/src/h5s.rs
This version is mostly a maintaince release, but introduces some new functions for allocation information which might be of use.
Fixes #153
> Update hdf5-src to use 1.10.7

- CHANGELOG.md
- src/globals.rs
- src/hl/plist/dataset_create.rs
- src/hl/plist/file_create.rs
- src/hl/selection.rs
`hdf5` calling `atexit` could create double free situations, where an orphaned thread would try to access a handle after it's been freed by the main thread.
The functioncality disabled by this involves [flushing data, closing objects, and cleaning up memory used](https://portal.hdfgroup.org/display/HDF5/H5_CLOSE). This is provided by `Drop` by rust, and pure rust programs will not be affected by this change.
In multi-language applications, care must be taken that all handles are closed by the programmer before program exit.
Fixes #159
> Prevent hdf5 calling atexit()

- CHANGELOG.md
- README.md
- examples/simple.rs
- src/error.rs
- src/globals.rs
- src/hl/dataspace.rs
- src/hl/datatype.rs
- src/hl/plist.rs
- src/hl/plist/dataset_access.rs
- src/hl/plist/dataset_create.rs
- src/hl/plist/file_access.rs
- src/hl/plist/file_create.rs
- src/hl/plist/link_create.rs
- src/hl/selection.rs
- src/lib.rs
- src/macros.rs
- src/test.rs
- tests/common/macros.rs
- tests/test_plist.rs
This introduces a wrapper around the errorstack, which should make the error stack a bit easier to reason about. Errors are now silenced by default
Fixes #155
Closes #158
> Leave the error stack unexpanded

- hdf5-sys/build.rs
The build failures described in #162 were most likely due to [TLS destructors behaving poorly with dynamic loading](https://github.com/nagisa/rust_libloading/issues/5). We work around this by leaving the library unloaded, which should not have any bad effects when used in the build script. `h5_dontatexit` did not have any effect on this bug.
Fixes #162
> Don't unload hdf5 in build script

- .github/workflows/ci.yml
See https://github.com/actions/virtual-environments/issues/3287 for the official notice
> Ubuntu 16.04 is no longer available

- hdf5-sys/src/h5a.rs
- hdf5-sys/src/h5d.rs
- hdf5-sys/src/h5e.rs
- hdf5-sys/src/h5f.rs
- hdf5-sys/src/h5g.rs
- hdf5-sys/src/h5o.rs
- hdf5-sys/src/h5r.rs
- hdf5-sys/src/h5s.rs
- hdf5-sys/src/h5t.rs
- hdf5-sys/src/h5z.rs
- src/hl/location.rs
I went through the [documentation](https://portal.hdfgroup.org/display/HDF5/HDF5) and added all functions which were marked as deprecated, mostly for completeness of the bindings. Most of these functions were deprecated in 1.8.0, which is a version we don't support.
I've also fixed up the name of some structs to be consistent with the naming in 1.12.0, and made sure we have aliases for these to remain compatible with other supported versions.
Comments on objects are officially deprecated in favor of attributes. I've added the `deprecated` attribute on the set/clear_comment in the top crate.
FIxes #114
> Add deprecated functions and deprecation warnings

- CHANGELOG.md
- hdf5-derive/src/lib.rs
- hdf5-derive/tests/compile-fail/struct-c-repr.stderr
- hdf5-derive/tests/compile-fail/struct-no-repr.rs
- hdf5-derive/tests/compile-fail/struct-no-repr.stderr
- hdf5-derive/tests/compile-fail/tuple-struct-c-repr.stderr
- hdf5-derive/tests/compile-fail/tuple-struct-no-repr.rs
- hdf5-derive/tests/compile-fail/tuple-struct-no-repr.stderr
- hdf5-derive/tests/test.rs
> Add support for `#[repr(packed)]` and `#[repr(transparent)]` in hdf5-derive

- CHANGELOG.md
- hdf5-sys/src/h5p.rs
- src/hl/dataset.rs
It turns out there is a fragment specifier for features: https://veykril.github.io/tlborm/decl-macros/minutiae/fragment-specifiers.html#meta
> Simplify feature expansion in macro

- .github/workflows/ci.yml
- hdf5-src/Cargo.toml
- hdf5-sys/Cargo.toml
- hdf5-sys/build.rs
- hdf5-sys/src/h5.rs
- hdf5-sys/src/h5a.rs
- hdf5-sys/src/h5d.rs
- hdf5-sys/src/h5e.rs
- hdf5-sys/src/h5es.rs
- hdf5-sys/src/h5f.rs
- hdf5-sys/src/h5fd.rs
- hdf5-sys/src/h5g.rs
- hdf5-sys/src/h5i.rs
- hdf5-sys/src/h5l.rs
- hdf5-sys/src/h5o.rs
- hdf5-sys/src/h5p.rs
- hdf5-sys/src/h5r.rs
- hdf5-sys/src/h5t.rs
- hdf5-sys/src/h5vl.rs
- hdf5-sys/src/lib.rs
- src/error.rs
- src/globals.rs
- src/hl/dataspace.rs
- src/hl/file.rs
- src/hl/group.rs
This PR adds 1.13 as a supported version, but does not use any of the new functionality.
The list of changes are found here: https://confluence.hdfgroup.org/display/support/HDF5%201.13.0#compatibility1130
> Support hdf5 version 1.13

- CHANGELOG.md
- hdf5-derive/Cargo.toml
- hdf5-derive/src/lib.rs
- hdf5-derive/tests/compile-fail/empty-enum.stderr
- hdf5-derive/tests/compile-fail/empty-struct.stderr
- hdf5-derive/tests/compile-fail/empty-tuple-struct.stderr
- hdf5-derive/tests/compile-fail/enum-no-repr.stderr
- hdf5-derive/tests/compile-fail/enum-non-scalar.stderr
- hdf5-derive/tests/compile-fail/pd-empty-struct.stderr
- hdf5-derive/tests/compile-fail/pd-empty-tuple-struct.stderr
- hdf5-derive/tests/compile-fail/struct-no-repr.stderr
- hdf5-derive/tests/compile-fail/tuple-struct-no-repr.stderr
- hdf5-derive/tests/compile-fail/unit-struct.stderr
As mentioned in #191 it would improve on the error messages to include the span. This highlights the struct/enum instead of giving the general `proc_macro panicked` and the message in the help section.
> Use proc-macro-error

- hdf5-sys/src/h5vl.rs
The previous macro would always match on the second item even if more than one variant was present
> Move catch-all in match after variants

- CHANGELOG.md
- src/error.rs
- src/hl.rs
- src/hl/container.rs
- src/lib.rs
- tests/test_dataset.rs
The design is based on io::Cursor. This PR only addresses datasets. I don't think it makes sense to also support io::Read for attributes since the whole advantage of io::Read is to only read the relevant part and not all bytes at once.
Currently I get the following error during H5DRead:
```
Error: IoError(Custom { kind: Other, error: "H5Dread(): can't read data: not a datatype" })
```
Closes #193
> Add ByteReader implementing io::Read and io::Seek

- CHANGELOG.md
- src/hl/plist.rs
- src/hl/plist/dataset_access.rs
- src/hl/plist/dataset_create.rs
- src/hl/plist/file_access.rs
- src/hl/plist/file_create.rs
- src/hl/plist/link_create.rs
Fixes #218. On the the bug in the issue memory usage decreases from 100MB++ to less than 50kB
@stormmathisen and @smutch Would be great if you tested this
> Use H5Pisa_class to circumvent bug

- hdf5-derive/src/lib.rs
- hdf5-derive/tests/test.rs
Creating unaligned references now causes a compile-time error, so this change uses `std::ptr::addr_of!` to compute struct field offsets instead.
> Avoid creating unaligned ref in H5Type derive macro

- .github/workflows/ci.yml
- CHANGELOG.md
- hdf5-sys/build.rs
- hdf5-sys/src/h5d.rs
The work done to support 1.13.0 means 1.14.0 is trivial to support
> Support hdf5 1.14.0

- CHANGELOG.md
- hdf5/src/hl.rs
- hdf5/src/hl/chunks.rs
- hdf5/src/hl/dataset.rs
- hdf5/src/lib.rs
This exposes the new chunk iterator in hdf5 1.14
> Chunks iterator

- CHANGELOG.md
- hdf5/src/hl/dataset.rs
- hdf5/src/hl/filters.rs
- hdf5/src/hl/plist/dataset_create.rs
The behaviour in `h5py` is to raise an error when trying to apply chunking/compression filters to dataset. This PR adds the same behaviour.
Fixes #212
> Add check for chunking of dataset for filters

- CHANGELOG.md
- hdf5-types/Cargo.toml
- hdf5-types/src/complex.rs
- hdf5-types/src/lib.rs
> Implement H5Type for complex

- .github/workflows/ci.yml
Replaces [actions-rs/toolchain](https://github.com/actions-rs/toolchain/) with [dtolnay/rust-toolchain](https://github.com/dtolnay/rust-toolchain) since the former is showing deprecation warnings and is unmaintained.
Fixes #241 (no idea why this is suddenly working again)
> Switch GitHub CI to dtolnay/rust-toolchain

- .github/workflows/ci.yml
- CHANGELOG.md
- hdf5-src/Cargo.toml
- hdf5-sys/Cargo.toml
- hdf5-sys/build.rs
- hdf5/Cargo.toml
Expands on the idea of @ajtribick in #204
> Use weak features in Cargo.toml

- CHANGELOG.md
- hdf5-sys/build.rs
- hdf5-sys/src/h5.rs
- hdf5-sys/src/h5a.rs
- hdf5-sys/src/h5d.rs
- hdf5-sys/src/h5e.rs
- hdf5-sys/src/h5f.rs
- hdf5-sys/src/h5fd.rs
- hdf5-sys/src/h5g.rs
- hdf5-sys/src/h5i.rs
- hdf5-sys/src/h5l.rs
- hdf5-sys/src/h5o.rs
- hdf5-sys/src/h5p.rs
- hdf5-sys/src/h5pl.rs
- hdf5-sys/src/h5r.rs
- hdf5-sys/src/h5t.rs
- hdf5-sys/src/h5vl.rs
- hdf5-sys/src/lib.rs
- hdf5/src/error.rs
- hdf5/src/globals.rs
- hdf5/src/hl/chunks.rs
The HDF5 1.13 series was only a preview and requires some workarounds. Simplify by only supporting 1.14.
Adds 1.14.1 as supported since only a couple of new functions were added. These have not been included, but we are not aiming to cover all of HDF5 (already missing VFD etc.)
Fixed a small bug in `ChunkInfo`
> Remove 1.13 support

- .github/workflows/ci.yml
- hdf5-sys/build.rs
- hdf5/build.rs
- hdf5/tests/test_dataset.rs
A meta-PR targeting the branch of #246
> Only run test_issue_223 when deflate filter is avail

- hdf5-sys/src/h5l.rs
Replace incorrect `H5L_info1_t__u` with `H5L_info2_t__u`. Since `H5L_info1_t__u` does not have the same size as `H5L_info2_t__u`, this bug resulted in 8 bytes of stack memory outside the allocated region being overwritten by the hdf5 C-library for example when using `H5Lget_info2`.
Since `Debug` can no longer be derived, add a manual implementation for the struct `H5L_info2_t` in order to correctly match the variant of `H5L_info2_t__u` to the link type.
Additionally, add methods to access the union fields of `H5L_info2_t__u`.
> Fix definition of `H5L_info2_t`

- hdf5-sys/src/h5.rs
- hdf5-sys/src/h5a.rs
- hdf5-sys/src/h5d.rs
- hdf5-sys/src/h5es.rs
- hdf5-sys/src/h5fd.rs
- hdf5-sys/src/h5i.rs
- hdf5-sys/src/h5l.rs
- hdf5-sys/src/h5mm.rs
- hdf5-sys/src/h5o.rs
- hdf5-sys/src/h5p.rs
- hdf5-sys/src/h5vl.rs
- hdf5-sys/src/h5z.rs
- hdf5/src/error.rs
- hdf5/src/hl/attribute.rs
- hdf5/src/hl/chunks.rs
- hdf5/src/hl/filters/blosc.rs
- hdf5/src/hl/filters/lzf.rs
- hdf5/src/hl/group.rs
- hdf5/src/hl/plist.rs
- hdf5/src/hl/plist/file_access.rs
- hdf5/src/util.rs
Found various functions that should be `unsafe` since they take raw pointer arguments and must assume they point to valid data.
Made `string_from_fixed_bytes` panic on invalid UTF-8 instead of marking it unsafe, but marking it unsafe is a valid alternative if the `unwrap` call significantly reduces performance.
> Mark various internal functions as unsafe

- .github/workflows/ci.yml
- CHANGELOG.md
- hdf5/src/hl/plist/file_access.rs
> Only conditionally call H5Pset_evict_on_close

- .github/workflows/ci.yml
- Cargo.toml
- hdf5-derive/Cargo.toml
- hdf5-sys/Cargo.toml
- hdf5-sys/src/h5p.rs
- hdf5-sys/src/lib.rs
- hdf5/Cargo.toml
- hdf5/src/class.rs
- hdf5/src/error.rs
- hdf5/src/hl/container.rs
- hdf5/src/hl/dataset.rs
- hdf5/src/hl/extents.rs
- hdf5/src/hl/filters.rs
- hdf5/src/hl/filters/blosc.rs
- hdf5/src/hl/filters/lzf.rs
- hdf5/src/hl/plist/dataset_access.rs
- hdf5/src/hl/plist/dataset_create.rs
- hdf5/src/hl/plist/file_access.rs
- hdf5/src/hl/plist/file_create.rs
- hdf5/src/hl/plist/link_create.rs
- hdf5/src/hl/selection.rs
- hdf5/src/lib.rs
Some long overdue maintenance updates.
(We should prob release a version soon, are we still stuck with the 1.14 problem?..)
> Maintenance updates

- hdf5-types/src/array.rs
- hdf5-types/src/string.rs
Closes #269 
@mulimoen Thank you for the feedback. I have added Send + Sync to the `VarLen...` types including comments to justify that (hopefully accurately).
> Implement Send+Sync for VarLenAscii/Unicode/Array

- .github/workflows/ci.yml
For #285.
* Alters conda to install miniconda as isn't preinstalled on new mac runners.
* Force to stay on an x86 Mac runner for 1.8 and 1.10.
* Operation on the Arm Mac runner for newer versions with switch for conda to use the arm distributables.
> Fix Conda Installs on Mac in CI

- .github/workflows/ci.yml
* Remove HDF5 1.8 from the brew tests - no longer available.
* Limit Wine tests to Rust 1.75 to maintain compatilibity with the installed wine version. #286
> fix: Unavailable Versions in CI
